spring.application.name=mybahaya-backend
server.port=8080
server.address=0.0.0.0
# Deactivate local docker engine checks since infrastructure is live on Hetzner
spring.docker.compose.enabled=false

# Firebase service account key file path (set this as an environment variable)
firebase.service-account-path=${FIREBASE_SERVICE_ACCOUNT_PATH}

# Allow image uploads up to 50MB (default is only 1MB)
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

# Hetzner MinIO Configurations
minio.url=http://178.105.158.80:9000
minio.access.key=${MINIO_ROOT_USER}
minio.secret.key=${MINIO_ROOT_PASSWORD}

minio.bucket.evidence=evidence
minio.bucket.profiles=profiles
minio.bucket.reports=reports
minio.bucket.system=system