// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByrfe5ptARXB3P8npOTHhVoxMau6f1z6w',
    appId: '1:671526838889:web:7766f9d2e7e248dcc638f8',
    messagingSenderId: '671526838889',
    projectId: 'mybahaya-app',
    authDomain: 'mybahaya-app.firebaseapp.com',
    storageBucket: 'mybahaya-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCTexkSDmxwd0OCA-rapjnngMihLSCgqw',
    appId: '1:671526838889:android:665bd59974eff595c638f8',
    messagingSenderId: '671526838889',
    projectId: 'mybahaya-app',
    storageBucket: 'mybahaya-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8A0fslQMvOctARrQawaqufh919VkfGVY',
    appId: '1:671526838889:ios:7cff130558279fa8c638f8',
    messagingSenderId: '671526838889',
    projectId: 'mybahaya-app',
    storageBucket: 'mybahaya-app.firebasestorage.app',
    iosBundleId: 'com.shukri.mybahaya',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8A0fslQMvOctARrQawaqufh919VkfGVY',
    appId: '1:671526838889:ios:e2551f2576a7376cc638f8',
    messagingSenderId: '671526838889',
    projectId: 'mybahaya-app',
    storageBucket: 'mybahaya-app.firebasestorage.app',
    iosBundleId: 'com.example.mybahaya',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyByrfe5ptARXB3P8npOTHhVoxMau6f1z6w',
    appId: '1:671526838889:web:c75b8923ff7723c8c638f8',
    messagingSenderId: '671526838889',
    projectId: 'mybahaya-app',
    authDomain: 'mybahaya-app.firebaseapp.com',
    storageBucket: 'mybahaya-app.firebasestorage.app',
  );
}
