// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // Web config (from Firebase console → Project Settings → Web app)
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCw63F4hFRDHGAXhhAlZJ-cT8M643MSisw',
    appId: '1:491193659854:web:dfd34cbfb22ba66458bb9f',
    messagingSenderId: '491193659854',
    projectId: 'mybahaya-fyp',
    authDomain: 'mybahaya-fyp.firebaseapp.com',
    storageBucket: 'mybahaya-fyp.firebasestorage.app',
  );

  // Android config (from google-services.json)
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCGSsOK6tscy2gw6O0FdM17wl4K0O4qvk',
    appId: '1:491193659854:android:82b4522b63e2f99a58bb9f',
    messagingSenderId: '491193659854',
    projectId: 'mybahaya-fyp',
    storageBucket: 'mybahaya-fyp.firebasestorage.app',
  );

  // iOS config (from GoogleService-Info.plist)
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9DC-v4y7WArPNTqC6kVBUFcEUEjdcORk',
    appId: '1:491193659854:ios:5189fa10661685d658bb9f',
    messagingSenderId: '491193659854',
    projectId: 'mybahaya-fyp',
    storageBucket: 'mybahaya-fyp.firebasestorage.app',
    iosBundleId: 'com.shukri.mybahaya',
  );

  // macOS uses same values as iOS
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9DC-v4y7WArPNTqC6kVBUFcEUEjdcORk',
    appId: '1:491193659854:ios:5189fa10661685d658bb9f',
    messagingSenderId: '491193659854',
    projectId: 'mybahaya-fyp',
    storageBucket: 'mybahaya-fyp.firebasestorage.app',
    iosBundleId: 'com.shukri.mybahaya',
  );

  // Windows uses same values as web
  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCw63F4hFRDHGAXhhAlZJ-cT8M643MSisw',
    appId: '1:491193659854:web:dfd34cbfb22ba66458bb9f',
    messagingSenderId: '491193659854',
    projectId: 'mybahaya-fyp',
    authDomain: 'mybahaya-fyp.firebaseapp.com',
    storageBucket: 'mybahaya-fyp.firebasestorage.app',
  );
}
